---
title: "W12: Regression Output"
author: "Kai"
date: "2023-12-01"
output:
  pdf_document:
    latex_engine: xelatex
header-includes:
- \usepackage{xeCJK}
- \usepackage{fontspec}
- \usepackage{url}
- \usepackage{xcolor}
- \definecolor{mycolor}{RGB}{255,0,0}
- \setCJKmainfont{標楷體}
- \usepackage{setspace}
- \usepackage{indentfirst}
- \usepackage{textgreek}
- \usepackage{dcolumn}
- \usepackage{float}
fontsize: 10.5pt
classoption: portrait
editor_options: 
  markdown: 
    wrap: 72
---

```{r setup, include=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tinytex)
```

```{r, warning=FALSE, message=FALSE}
library(haven)
library(tidyverse)
library(DescTools)
library(sjmisc)
library(stats)
library(ggplot2)
library(labelled)
library(stargazer)
```

```{r, warning=FALSE}
ESS8 <- read_dta('C:/Users/User/Documents/R/Workspace/112 (1) Statistics@NTU/Week 12/HW/ESS8e02_3/ESS8e02_3.dta')
DV <- ESS8 %>%
  select(eneffap, rdcenr, inctxff, sbsrnen, banhhap)
IV <- ESS8 %>%
  select(cflsenr, ownrdcc, lklmten, lkredcc)
CV <-  ESS8 %>%
  select(gndr, yrbrn, inwyye, lrscale, cntry)

#Data cleaning: Dependent variables#
norm_scale <- function(vec) {
  (vec - min(vec, na.rm = T)) / (max(vec, na.rm = T) - min(vec, na.rm = T))
}                                                                   
#特徵縮放(feature scaling)公式，以處理編碼為1~5或1~6的變數

DV <- DV %>%
  mutate(eneffap = remove_labels(eneffap, user_na_to_na = T)) %>%   
  mutate(rdcenr = remove_labels(rdcenr, user_na_to_na = T)) %>%
  mutate(inctxff = remove_labels(inctxff, user_na_to_na = T)) %>%
  mutate(sbsrnen = remove_labels(sbsrnen, user_na_to_na = T)) %>%
  mutate(banhhap = remove_labels(banhhap, user_na_to_na = T)) %>%   
  #將兩個依變數涉及的五個變數，去除原Stata檔的標籤
  mutate(inctxff = 6 - `inctxff`) %>%                               
  mutate(sbsrnen = 6 - `sbsrnen`) %>%
  mutate(banhhap = 6 - `banhhap`) %>%                               
  #將依變數二涉及的三個變數反向編碼，因為是1~5的編碼，故用6去減
  mutate(eneffap = `eneffap` / 10) %>%                              
  #eneffap：將0~10的編碼，轉變成0~1之間的連續變數
  set_na(rdcenr, na=c(55, "NA")) %>%
  mutate(rdcenr = norm_scale(rdcenr)) %>%                           
  #rdcenr：將1~6的編碼，利用特徵縮放的方式，轉變成0~1之間的連續變數
  mutate(inctxff = norm_scale(inctxff)) %>%                         
  #inctxff：將1~5的編碼，利用特徵縮放的方式，轉變成0~1之間的連續變數
  mutate(sbsrnen = norm_scale(sbsrnen)) %>%                         
  #sbsrnen：將1~5的編碼，利用特徵縮放的方式，轉變成0~1之間的連續變數
  mutate(banhhap = norm_scale(banhhap))
  #banhhap：將1~5的編碼，利用特徵縮放的方式，轉變成0~1之間的連續變數

DV1 <- DV %>%
  select(eneffap, rdcenr) %>%
  mutate(DV1 = rowMeans(DV[, c(1:2)], na.rm = T))               
  #將eneffap和rdcenr變數合併(rowMeans)，成為依變數一
DV2 <- DV %>%
  select(inctxff, sbsrnen, banhhap) %>%
  mutate(DV2 = rowMeans(DV[, c(3:5)], na.rm = T)) %>%
  #將inctxff, sbsrnen和banhhap變數合併(rowMeans)，成為依變數二
  round(2)
DV <- bind_cols(DV1, DV2)

#Data cleaning: Independent variables#
IV <- IV %>%
  mutate(cflsenr = remove_labels(cflsenr, user_na_to_na = T)) %>%   
  mutate(ownrdcc = remove_labels(ownrdcc, user_na_to_na = T)) %>%
  mutate(lklmten = remove_labels(lklmten, user_na_to_na = T)) %>%
  mutate(lkredcc = remove_labels(lkredcc, user_na_to_na = T)) %>%    
  #將四個自變數涉及的四個變數，去除原Stata檔的標籤
  mutate(cflsenr = `cflsenr` / 10) %>%                               
  #cflsenr：將0~10的編碼，轉變成0~1之間的連續變數
  mutate(ownrdcc = `ownrdcc` / 10) %>%                               
  #ownrdcc：將0~10的編碼，轉變成0~1之間的連續變數
  mutate(lklmten = `lklmten` / 10) %>%                               
  #lklmten：將0~10的編碼，轉變成0~1之間的連續變數
  mutate(lkredcc = `lkredcc` / 10)                                   
  #lkredcc：將0~10的編碼，轉變成0~1之間的連續變數

#Data cleaning: Control variables#
CV <- CV %>%
  mutate(gndr = remove_labels(gndr, user_na_to_na = T)) %>%
  mutate(inwyye = remove_labels(inwyye, user_na_to_na = T)) %>%
  mutate(yrbrn = remove_labels(yrbrn, user_na_to_na = T)) %>%
  mutate(lrscale = remove_labels(lrscale, user_na_to_na = T)) %>%               
  #去除gndr、inwyye、yrbrn、lrscale變數的原Stata檔標籤
  mutate(gndr = factor(gndr, levels = c(1,2), labels=c("Male", "Female"))) %>%  
  #gndr：1 = Male; 2 = Female
  mutate(age = `inwyye` - `yrbrn`) %>%
  mutate(age_grp = case_when(
    age < 25 ~ "Under 25",
    age %in% c(25:34) ~ "25~34",
    age %in% c(35:44) ~ "35~44",
    age %in% c(45:54) ~ "45~54",
    age %in% c(55:64) ~ "55~64",
    age %in% c(65:74) ~ "65~74",
    age %in% c(75:85) ~ "75~85",
    age > 85 ~ "Above 85")
    ) %>%                                       
  #age：首先將每一個受訪者的受訪年減去出生年，得出年齡之後，先分成八組年齡層(age_grp)
  mutate(age_grp = factor(age_grp, levels = c("Under 25", "25~34", "35~44", "45~54", "55~64", "65~74", "75~85", "Above 85"))) %>%
  mutate(age_grp = as.numeric(age_grp)) %>%     
  #age_grp：得到八組年齡層之後，重新編碼成1~8，成為區間變數
  mutate(lrscale = `lrscale` / 10)              
  #lrscale：將0~10的編碼，轉變成0~1之間的連續變數

#General dataset#
lm_data <- bind_cols(DV, IV, CV)                
#將以處理好的依變數、自變數、控制變數合併成總表，方便後續跑統計
lm_data <- lm_data[complete.cases(lm_data), ]   
#並且去除NA，像作者一樣統一樣本數
```

### Table 1
```{r, warning=FALSE, eval=FALSE, results='hide'}
#Table 1#
#Row 1#
cor.test(lm_data$cflsenr, lm_data$ownrdcc, conf.level = 0.95)
#Self-efficacy (IV1) v.s. Personal outcome expectancy (IV2)
cor.test(lm_data$cflsenr, lm_data$lklmten, conf.level = 0.95)
#Self-efficacy (IV1) v.s. Collective self-efficacy (IV3)
cor.test(lm_data$cflsenr, lm_data$lkredcc, conf.level = 0.95)
#Self-efficacy (IV1) v.s. Collective outcome expectancy (IV4)

#Row 2#
cor.test(lm_data$ownrdcc, lm_data$lklmten, conf.level = 0.95)
#Personal outcome expectancy (IV2) v.s. Collective self-efficacy (IV3)
cor.test(lm_data$ownrdcc, lm_data$lkredcc, conf.level = 0.95)
#Personal outcome expectancy (IV2) v.s. Collective outcome expectancy (IV4)

#Row 3#
cor.test(lm_data$lklmten, lm_data$lkredcc, conf.level = 0.95)
#Collective self-efficacy (IV3) v.s. Collective outcome expectancy (IV4)
```

+---------------+--------------+--------------+----------------+
|               | Personal     | Collective   | Collective     |
|               | outcome      | efficacy     | outcome        |
|               | expectancy   |              | expectancy     |
+===============+==============+==============+================+
| Self efficacy | 0.227\*\*\*  | 0.144\*\*\*  | 0.209\*\*\*    |
|               |              |              |                |
|               | (0.217,      | (0.134,      | (0.200, 0.220) |
|               | 0.237)       | 0.154)       |                |
+---------------+--------------+--------------+----------------+
|               |              |              |                |
+---------------+--------------+--------------+----------------+
| Personal      |              | 0.414\*\*\*  | 0.433\*\*\*    |
| outcome       |              |              |                |
| expectancy    |              | (0.405,      | (0.425, 0.442) |
|               |              | 0.423)       |                |
+---------------+--------------+--------------+----------------+
|               |              |              |                |
+---------------+--------------+--------------+----------------+
| Collective    |              |              | 0.316\*\*\*    |
| efficacy      |              |              |                |
|               |              |              | (0.306, 0.326) |
+---------------+--------------+--------------+----------------+
|               |              |              |                |
+---------------+--------------+--------------+----------------+

\*\*\*p \< 0.001.

95% confidence intervals are reported in parentheses under each
coefficient.

### Table 2: 完整版模型 (參考自補充資料的Table S6)
```{r, results='hide', message=FALSE}
AT <- relevel(factor(lm_data$cntry), ref = "AT")              
#cntry：設奧地利(AT)為對照組
male <- relevel(lm_data$gndr, ref = "Male")                     
#gndr：觀察作者的模型之後，他們似乎將男性(Male)當作對照組

#Table 2#
m1 <- lm(DV1 ~ cflsenr + lrscale + male + age_grp + AT, data = lm_data)
summary(m1)
m2 <- lm(DV1 ~ ownrdcc + lrscale + male + age_grp + AT, data = lm_data)
summary(m2)
m3 <- lm(DV1 ~ lklmten + lrscale + male + age_grp + AT, data = lm_data)
summary(m3)
m4 <- lm(DV1 ~ lkredcc + lrscale + male + age_grp + AT, data = lm_data)
summary(m4)
m5 <- lm(DV1 ~ cflsenr + ownrdcc + lklmten + lkredcc +
           lrscale + male + age_grp + AT, data = lm_data)
summary(m5)
t2 <- stargazer(m1, m2, m3, m4, m5,
          dep.var.labels = "Behavioral Intention",
          covariate.labels = c("SE", "POE", "CE", "COE", "Political Ideology",
                               "Gender (Male)", "Age", "Belgium",
                               "Switzerland", "Czechia", "Germany", "Estonia",
                               "Spain", "Finland", "France", "UK", "Hungary",
                               "Ireland", "Israel", "Iceland", "Italy",
                               "Lithuania", "Netherlands", "Norway", "Poland",
                               "Portugal", "Russian Federation", "Sweden",
                               "Slovenia"),
          omit.stat = c("f", "ser"),
          ci = T, ci.level = 0.95,
          no.space = T, notes.append = T, align = T, float = F, header = F,
          star.char = c("*", "**", "***"),
          star.cutoffs = c(0.05, 0.01, 0.001),
          column.sep.width = "5pt", font.size = "footnotesize")
```

```{r, results='asis', message=FALSE}
cat('\\begin{center}', t2, '\\end{center}')  #將表格置中
```

### Table S10
```{r, results='hide', message=FALSE}
#Table S10#
m6 <- lm(DV2 ~ cflsenr + lrscale + male + age_grp + AT, data = lm_data)
summary(m6)
m7 <- lm(DV2 ~ ownrdcc + lrscale + male + age_grp + AT, data = lm_data)
summary(m7)
m8 <- lm(DV2 ~ lklmten + lrscale + male + age_grp + AT, data = lm_data)
summary(m8)
m9 <- lm(DV2 ~ lkredcc + lrscale + male + age_grp + AT, data = lm_data)
summary(m9)
m10 <- lm(DV2 ~ cflsenr + ownrdcc + lklmten + lkredcc +
           lrscale + male + age_grp + AT, data = lm_data)
summary(m10)
ts10 <- stargazer(m6, m7, m8, m9, m10,
          dep.var.labels = "Policy support",
          covariate.labels = c("SE", "POE", "CE", "COE", "Political Ideology",
                               "Gender (Male)", "Age", "Belgium",
                               "Switzerland", "Czechia", "Germany", "Estonia",
                               "Spain", "Finland", "France", "UK", "Hungary",
                               "Ireland", "Israel", "Iceland", "Italy",
                               "Lithuania", "Netherlands", "Norway", "Poland",
                               "Portugal", "Russian Federation", "Sweden",
                               "Slovenia"),
          omit.stat = c("f", "ser"),
          ci = T, ci.level = 0.95,
          no.space = T, notes.append = T, align = T, float = F, header = F,
          star.char = c("*", "**", "***"),
          star.cutoffs = c(0.05, 0.01, 0.001),
          column.sep.width = "5pt", font.size = "footnotesize")
```

```{r results='asis', message=FALSE}
cat('\\begin{center}', ts10, '\\end{center}')
```

### Table 3: 完整版模型 (參考自補充資料的Table S12)
```{r, results='hide', message=FALSE}
#Table 3#
m11 <- lm(DV1 ~ cflsenr * ownrdcc + lklmten * lkredcc +
           lrscale + male + age_grp + AT, data = lm_data)
summary(m11)
m12 <- lm(DV2 ~ cflsenr * ownrdcc + lklmten * lkredcc +
           lrscale + male + age_grp + AT, data = lm_data)
summary(m12)
t3 <- stargazer(m11, m12,
          dep.var.labels = c("Behavioral Intention", "Policy support"),
          covariate.labels = c("SE", "POE", "CE", "COE", "Political Ideology",
                               "Gender (Male)", "Age", "Belgium",
                               "Switzerland", "Czechia", "Germany", "Estonia",
                               "Spain", "Finland", "France", "UK", "Hungary",
                               "Ireland", "Israel", "Iceland", "Italy",
                               "Lithuania", "Netherlands", "Norway", "Poland",
                               "Portugal", "Russian Federation", "Sweden",
                               "Slovenia", "SE × POE", "CE × COE"),
          omit.stat = c("f", "ser"),
          ci = T, ci.level = 0.95,
          no.space = T, notes.append = T, align = T, float = F, header = F,
          star.char = c("*", "**", "***"),
          star.cutoffs = c(0.05, 0.01, 0.001),
          column.sep.width = "8pt", font.size = "footnotesize")
```

```{r, results='asis', message=FALSE}
cat('\\begin{center}', t3, '\\end{center}')
```